# Generated by Django 5.2.8 on 2025-11-12 16:28

import agents.models
import django.core.validators
import django.db.models.deletion
import storages.backends.s3
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=agents.models.agent_profile_upload_to)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, default='Kenya', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum deposit in KES', max_digits=14, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum deposit in KES', max_digits=14, null=True)),
                ('response_time', models.CharField(blank=True, default='Within 5 minutes', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('mpesa_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_link', models.URLField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_swift', models.CharField(blank=True, max_length=11, null=True)),
                ('deposit_rate_kes_to_usd', models.DecimalField(decimal_places=2, default=130.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('withdrawal_rate_usd_to_kes', models.DecimalField(decimal_places=2, default=129.5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(100)])),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], db_index=True, editable=False, max_length=30)),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('screenshot', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=agents.models.payment_screenshot_upload_to)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_deposits', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_method'], name='agents_agen_payment_0c74cc_idx'), models.Index(fields=['status'], name='agents_agen_status_d281c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(10)])),
                ('amount_kes', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], db_index=True, editable=False, max_length=30)),
                ('user_paypal_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('user_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_bank_swift', models.CharField(blank=True, max_length=11, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP'), ('otp_verified', 'OTP Verified'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_otp', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_method'], name='agents_agen_payment_0a7e96_idx'), models.Index(fields=['status'], name='agents_agen_status_f74268_idx')],
            },
        ),
    ]
