# Generated by Django 5.2.7 on 2025-11-02 12:31

import agents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=agents.models.agent_profile_upload_to)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_link', models.URLField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_swift', models.CharField(blank=True, max_length=20, null=True)),
                ('deposit_rate_kes_to_usd', models.DecimalField(decimal_places=4, default=130.0, help_text='KSH per 1 USD (e.g., 130.50)', max_digits=10)),
                ('withdrawal_rate_usd_to_kes', models.DecimalField(decimal_places=4, default=129.5, help_text='KSH per 1 USD for withdrawal', max_digits=10)),
                ('instructions', models.TextField(help_text='How to pay this agent (e.g., send to 0712345678, PayPal to agent@email.com)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(10)])),
                ('amount_kes', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP'), ('otp_verified', 'OTP Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_otp', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(100)])),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('transaction_code', models.CharField(help_text='M-Pesa / PayPal / Bank Ref', max_length=50)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=agents.models.payment_screenshot_upload_to)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_deposits', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agent', 'transaction_code')},
            },
        ),
    ]
