# Generated by Django 5.2.7 on 2025-11-03 05:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        ('agents', '0002_agent_location_agent_max_amount_agent_min_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='deposit_rate_kes_to_usd',
            field=models.DecimalField(decimal_places=2, default=130.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum deposit in KES', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum deposit in KES', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='withdrawal_rate_usd_to_kes',
            field=models.DecimalField(decimal_places=2, default=129.5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='transaction_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
