# Generated by Django 5.2.7 on 2025-11-03 10:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        ('agents', '0003_alter_agent_bank_swift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdeposit',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentdeposit',
            name='payment_method',
            field=models.CharField(
                choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')],
                max_length=20,
                editable=False,
                blank=True,  # Allow blank temporarily
            ),
        ),
        migrations.AddField(
            model_name='agentdeposit',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentwithdrawal',
            name='payment_method',
            field=models.CharField(
                choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')],
                max_length=20,
                editable=False,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending_otp', 'Pending OTP'), ('otp_verified', 'OTP Verified'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_otp', max_length=15),
        ),
        migrations.AddIndex(
            model_name='agentdeposit',
            index=models.Index(fields=['payment_method'], name='agents_agen_payment_0c74cc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdeposit',
            index=models.Index(fields=['status'], name='agents_agen_status_d281c7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentwithdrawal',
            index=models.Index(fields=['payment_method'], name='agents_agen_payment_0a7e96_idx'),
        ),
        migrations.AddIndex(
            model_name='agentwithdrawal',
            index=models.Index(fields=['status'], name='agents_agen_status_f74268_idx'),
        ),
    ]
