# Generated by Django 5.2.7 on 2025-11-04 18:02

import agents.models
import django.core.validators
import django.db.models.deletion
import storages.backends.s3
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        ('agents', '0005_agentdeposit_updated_at_agentwithdrawal_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentdeposit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=agents.models.agent_profile_upload_to),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='account',
            field=models.ForeignKey(limit_choices_to={'account_type__in': ['standard', 'pro-fx']}, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=agents.models.payment_screenshot_upload_to),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
