# Generated by Django 5.2.7 on 2025-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_populate_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentdeposit',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], db_index=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentwithdrawal',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], db_index=True, editable=False, max_length=30),
        ),
    ]
