# Generated by Django 5.2.7 on 2025-12-26 13:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        ('trading', '0009_robot_discounted_price_userrobot_purchased_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio or trading strategy description')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('min_allocation', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('performance_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentage of profits charged as fee (0-50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MinValueValidator(Decimal('50.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this trader is available for copying')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text="Amount allocated from user's account for copying", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('max_drawdown_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Max loss percentage before auto-stop (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_subscriptions', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='copy_trading.trader')),
            ],
            options={
                'unique_together': {('user', 'trader', 'account')},
            },
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('buy', 'Buy/Rise/Touch'), ('sell', 'Sell/Fall/No Touch')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_spot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.market')),
                ('trade_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.tradetype')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='copy_trading.trader')),
            ],
        ),
        migrations.CreateModel(
            name='CopiedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaled_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_from', to='trading.trade')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_trades', to='copy_trading.copysubscription')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_instances', to='copy_trading.tradesignal')),
            ],
        ),
    ]
