# Generated by Django 5.2.7 on 2025-12-26 14:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copysubscription',
            name='max_drawdown_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Max loss percentage before auto-stop (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='trader',
            name='performance_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentage of profits charged as fee (0-50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))]),
        ),
    ]
