# Generated by Django 5.2.7 on 2025-12-27 08:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        ('copy_trading', '0002_alter_copysubscription_max_drawdown_percent_and_more'),
        ('trading', '0009_robot_discounted_price_userrobot_purchased_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='copysubscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tradesignal',
            name='closed_at',
        ),
        migrations.AlterField(
            model_name='copiedtrade',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_from', to='copy_trading.tradesignal'),
        ),
        migrations.AlterField(
            model_name='copiedtrade',
            name='trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.trade'),
        ),
        migrations.AlterField(
            model_name='copysubscription',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='copysubscription',
            name='max_drawdown_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='copysubscription',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_subscriptions', to='copy_trading.trader'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='performance_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))]),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='direction',
            field=models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='entry_spot',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='copysubscription',
            unique_together={('user', 'account', 'trader')},
        ),
    ]
