# Generated by Django 5.2.7 on 2026-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_seed_currency_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=20),
        ),
    ]
