# Generated by Django 5.2.7 on 2026-01-01 17:53

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(default=wallet.models.generate_reference_id, max_length=50),
        ),
    ]
