# Generated by Django 5.2.7 on 2026-01-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallettransaction_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
