# Generated by Django 5.2.7 on 2025-10-27 11:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('pip_value', models.DecimalField(decimal_places=5, default=Decimal('0.0001'), max_digits=10)),
                ('contract_size', models.IntegerField(default=100000)),
                ('spread', models.DecimalField(decimal_places=5, default=Decimal('0.0001'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('volume_lots', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sl', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('floating_p_l', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('leverage', models.IntegerField(default=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forex_positions', to='accounts.account')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forex.forexpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='ForexTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('realized_p_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_reason', models.CharField(max_length=10)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forex.position')),
            ],
        ),
    ]
