# Generated by Django 5.2.7 on 2025-10-27 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexpair',
            name='base_simulation_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('1.1000'), max_digits=10),
        ),
    ]
