# Generated by Django 5.2.7 on 2025-10-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_forexpair_base_simulation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexpair',
            name='default_time_frame',
            field=models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', max_length=3),
        ),
        migrations.AddField(
            model_name='position',
            name='time_frame',
            field=models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', max_length=3),
        ),
    ]
