# Generated by Django 5.2.7 on 2025-11-01 06:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_forexpair_default_time_frame_position_time_frame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_markets', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Crypto'), ('indices', 'Indices'), ('commodities', 'Commodities')], max_length=20)),
                ('win_rate_sashi', models.IntegerField(default=90)),
                ('win_rate_normal', models.IntegerField(default=10)),
                ('stake_per_trade', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_trade_time', models.DateTimeField(blank=True, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.forexrobot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'robot')},
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('trade_result', models.CharField(blank=True, max_length=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forex.userrobot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
