# Generated by Django 5.2.7 on 2025-11-01 07:45

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_forexrobot_userrobot_botlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forexrobot',
            options={},
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='robots/'),
        ),
    ]
