# Generated by Django 5.2.7 on 2025-11-01 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0005_alter_forexrobot_options_alter_forexrobot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexrobot',
            name='profit_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Profit = stake × multiplier on win (e.g., 2.00 = 2:1 RR)', max_digits=5),
        ),
    ]
