# Generated by Django 5.2.7 on 2025-11-01 12:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0006_forexrobot_profit_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrobot',
            name='selected_pair',
            field=models.ForeignKey(blank=True, help_text='Pair to trade (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forex.forexpair'),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='stake_per_trade',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Stake amount per trade (overrides robot default)', max_digits=10),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='timeframe',
            field=models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '24 Hours')], default='M1', help_text='Chart timeframe for simulation', max_length=3),
        ),
    ]
