# Generated by Django 5.2.7 on 2025-12-20 14:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0007_userrobot_selected_pair_userrobot_stake_per_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexrobot',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this discounted price will be used instead of the original price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='stake_per_trade',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default stake per trade (can be overridden by user)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='win_rate_normal',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='forexrobot',
            name='win_rate_sashi',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
