# Generated by Django 5.2.8 on 2025-11-08 13:46

import django.core.validators
import django.db.models.deletion
import management.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_seed_currency_exchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_id', models.CharField(default=management.models.generate_management_id, max_length=20, unique=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(50)])),
                ('target_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_phone', models.CharField(max_length=15)),
                ('account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_password', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_target_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_verified', 'Payment Verified'), ('credentials_pending', 'Awaiting Credentials'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_request', to='wallet.wallettransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
