# Generated by Django 5.2.7 on 2025-12-17 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='managementrequest',
            name='payment_transaction',
        ),
        migrations.AddField(
            model_name='managementrequest',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementrequest',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='managementrequest',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='managementrequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='managementrequest',
            name='target_profit',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
