# Generated by Django 5.2.7 on 2025-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_managementrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementrequest',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('profx', 'ProFX')], default='standard', max_length=20),
        ),
    ]
