# Generated by Django 5.2.7 on 2026-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_managementrequest_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementrequest',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro-fx', 'ProFX')], default='standard', max_length=20),
        ),
    ]
