# Generated by Django 5.2.7 on 2025-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('standard', 'TradeRiser Standard'), ('pro', 'TradeRiser Pro'), ('islamic', 'TradeRiser Islamic'), ('options', 'TradeRiser Options'), ('crypto', 'TradeRiser Crypto'), ('demo', 'TradeRiser Demo'), ('pro-fx', 'TradeRiser Pro-FX')], max_length=50),
        ),
    ]
