# Generated by Django 5.2.7 on 2026-02-15 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_marketo_user_referral_code_user_referred_by'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(blank=True, upload_to='suspension_evidence/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Details of violation/evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Account Suspended'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspended At'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspended Until (Temporary)'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Suspension History'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='Suspension Reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_type',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='', max_length=20, verbose_name='Suspension Type'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referral_code'], name='accounts_us_referra_2cbfb5_idx'),
        ),
        migrations.AddField(
            model_name='suspensionevidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspensionevidence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_evidence', to=settings.AUTH_USER_MODEL),
        ),
    ]
