# Generated by Django 5.2.7 on 2025-12-02 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeTrader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('country_flag', models.CharField(default='🌍', max_length=10)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=160)),
                ('profit_fake', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Text Only'), ('image', 'Image + Caption'), ('video', 'Video'), ('chart', 'Chart Analysis'), ('win', 'Big Win Celebration'), ('loss', 'Reality Check')], default='text', max_length=20)),
                ('text', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fake_trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traderpulse.faketrader')),
                ('real_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='traderpulse_created_63c682_idx'), models.Index(fields=['is_ai_generated'], name='traderpulse_is_ai_g_047a23_idx')],
            },
        ),
    ]
