# Generated by Django 5.2.7 on 2025-10-25 16:26

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_delete_marketchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='robots/'),
        ),
    ]
