# Generated by Django 5.2.7 on 2026-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_robot_discounted_price_userrobot_purchased_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_copied',
            field=models.BooleanField(default=False),
        ),
    ]
