# Generated by Django 5.2.7 on 2026-01-05 07:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='current_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='signal',
            name='strength',
            field=models.FloatField(default=0.0),
        ),
    ]
